CMD_DEF(ADD,  ZERO_ARG)
CMD_DEF(SUB,  ZERO_ARG)
CMD_DEF(MUL,  ZERO_ARG)
CMD_DEF(DIV,  ZERO_ARG)

CMD_DEF(OUT,  ZERO_ARG)

CMD_DEF(CMP,   TWO_ARG)

CMD_DEF(PUSH,  ONE_ARG)
CMD_DEF(POP,   ONE_ARG)

CMD_DEF(JMP,   LBL_ARG)
CMD_DEF(JA,    LBL_ARG)
CMD_DEF(JAE,   LBL_ARG)
CMD_DEF(JB,    LBL_ARG)
CMD_DEF(JBE,   LBL_ARG)
CMD_DEF(JE,    LBL_ARG)
CMD_DEF(JNE,   LBL_ARG)
